import type { Metadata } from "next";
import "./globals.css";
import { GameProvider } from "@/context/GameContext";
import { AuroraBackground } from "@/components/ui/aurora-background";

import { Inter } from '@next/font/google';


import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "card game counting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body   className={`${geistSans.variable}  antialiased`} >
        <GameProvider>
          <AuroraBackground>
            {children}
          </AuroraBackground>
        </GameProvider>
      </body>
    </html>
  );
}
