import type { Metadata } from "next";
import "./globals.css";
import { GameProvider } from "@/context/GameContext";
import { AuroraBackground } from "@/components/ui/aurora-background";

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "card game counting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body   className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <GameProvider>
          <AuroraBackground>
            {children}
          </AuroraBackground>
        </GameProvider>
      </body>
    </html>
  );
}
